collections:
  pages:
    output: true
    permalink: /:name
  authors:
    output: true
    permalink: /blog/authors/:name
  publications:
    output: true
    permalink: /publications/:path
    sort_by: date

# Sets the default layout for the various types of pages:
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "collections/_publications"
    values:
      layout: "publication"
      section: publications
  - scope:
      path: "collections/_publications/conferences"
    values:
      publication_type: "conference"
  - scope:
      path: "collections/_publications/theses"
    values:
      publication_type: "thesis"
  - scope:
      path: "collections/_publications/bookchapters"
    values:
      publication_type: "bookchapter"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

timezone: Italy/Rome
encoding: UTF-8
collections_dir: collections
theme: null # Disables default theme from GitHub Pages

exclude: [README.md, install-dep.sh, Makefile, Gemfile, Gemfile.lock, LICENSE]
